def anal_エラーがあります(ERROR, FINALLY):
	try:
		print(x)
	except:
		print(ERROR)
	finally:
		print(FINALLY)